"use strict";

module.exports = {
    TokenskyAvatarDB: 'TokenskyAvatarDB',//数据库名称
    C2C_ACCOUNT: 'c2c_account',//用户账户表
    C2C_ACCOUNT_BANK: 'c2c_account_bank',//用户银行账户表
    HASHRATE_AGREEMENT_CONFIG: 'hashrate_agreement_config',//云算力服务协议配置表
    HASHRATE_CATEGORY: 'hashrate_category',//算力合约分类
    HASHRATE_ORDER: 'hashrate_order',//算力订单表
    HASHRATE_ORDER_PROFIT: 'hashrate_order_profit',//算力订单收益表
    HASHRATE_ORDER_TRANSACTION: 'hashrate_order_transaction',//订单交易关联表
    HASHRATE_SEND_BALANCE_RECORD: 'hashrate_send_balance_record',//算力资源资产发放记录表
    HASHRATE_TREATY: 'hashrate_treaty',//算力合约表
    OPERATION_BANNER: 'operation_banner',//BANNER
    OTC_APPEAL: 'otc_appeal',//申诉表
    OTC_COIN_LIST: 'otc_coin_list',//OTC货币类型表
    OTC_CONF: 'otc_conf',//otc配置表
    OTC_CONF_BAK: 'otc_conf_bak',//otc配置操作记录表
    OTC_ENTRUST_AUTO_CANCEL_RECORD: 'otc_entrust_auto_cancel_record',//委托单自动取消表
    OTC_ENTRUST_ORDER: 'otc_entrust_order',//委托单表
    OTC_ORDER: 'otc_order',//订单表
    OTC_ORDER_SMS: 'otc_order_sms',//订单短信表
    OTC_USER_FROZEN_BALANCE: 'otc_user_frozen_balance',//卖出委托冻结金币表
    RMS_BACKEND_USER: 'rms_backend_user',
    RMS_RESOURCE: 'rms_resource',
    RMS_ROLE: 'rms_role',
    RMS_ROLE_BACKENDUSER_REL: 'rms_role_backenduser_rel',
    RMS_ROLE_RESOURCE_REL: 'rms_role_resource_rel',
    ROLE_BLACK_LIST: 'role_black_list',
    TOKENSKY_ACCOUNT_BANK: 'tokensky_account_bank',//收款管理地址表
    TOKENSKY_ADDRESS_BOOK: 'tokensky_address_book',//地址簿表
    TOKENSKY_CHANGE_RECORD: 'tokensky_change_record',//用户操作改变纪录表
    TOKENSKY_CHECK: 'tokensky_check',
    TOKENSKY_CHONGBI_CONFIG: 'tokensky_chongbi_config',//充币配置表
    TOKENSKY_CHONGBI_CONFIG_BAK: 'tokensky_chongbi_config_bak',
    TOKENSKY_JIGUANG_REGISTRATIONID: 'tokensky_jiguang_registrationid',
    TOKENSKY_MESSAGE: 'tokensky_message',
    TOKENSKY_ORDER_IDS: 'tokensky_order_ids',
    TOKENSKY_REAL_AUTH: 'tokensky_real_auth',
    TOKENSKY_REAL_AUTH_INFO: 'tokensky_real_auth_info',
    TOKENSKY_SMS: 'tokensky_sms',
    TOKENSKY_TIBI_CONFIG: 'tokensky_tibi_config',
    TOKENSKY_TIBI_CONFIG_BAK: 'tokensky_tibi_config_bak',
    TOKENSKY_TRANSACTION_RECORD: 'tokensky_transaction_record',
    TOKENSKY_USER: 'tokensky_user',
    TOKENSKY_USER_ADDRESS: 'tokensky_user_address',
    TOKENSKY_USER_BALANCE: 'tokensky_user_balance',
    TOKENSKY_USER_BALANCE_COIN: 'tokensky_user_balance_coin',
    TOKENSKY_USER_CHONG_ELECTRICITY_ORDER: 'tokensky_user_chong_electricity_order',
    TOKENSKY_USER_DEPOSIT: 'tokensky_user_deposit',
    TOKENSKY_USER_ELECTRICITY_BALANCE: 'tokensky_user_electricity_balance',
    TOKENSKY_USER_TIBI: 'tokensky_user_tibi',
    TOKENSKY_USER_TOKEN: 'tokensky_user_token',
    TOKENSKY_OTC_CHAT_ROOM: 'tokensky_otc_chat_room',
    TOKENSKY_OTC_CHAT_RECORD: 'tokensky_otc_chat_record',
    TOKENSKY_USER_BALANCE_HASH: 'tokensky_user_balance_hash'
};
